### ISSUE TITLE
printing functionality

### ISSUE THREAD

**Issue by fortytw2** [pganalyze/pg_query_go#2]
along the same lines of `go/printer`, would be very nice to turn a `ParsetreeList` back into text (potentially allowing a decent autoformatter to be written). 

If this is already in the books / someone is working on it, that'd be great to know before I take a crack at it myself

**Comment by lfittl** [comment]
@fortytw2 Thats a very good idea, and something I'd like to do - but if you have time, nobody I know is working on it right now (including me), so its a good time to give it a try :)

You can take inspiration from pg_query, which has a somewhat complete set of deparsing rules: https://github.com/lfittl/pg_query/blob/master/lib/pg_query/deparse.rb

There is also the deparser written by @zhm for the Node.js library, which should have near-full coverage: https://github.com/zhm/pg-query-parser/blob/master/src/deparser.js

If I remember correctly, for the latter, @zhm used Postgres' own regression test suite as a source of possible SQL queries, parsed them once (remembered that as e.g. `a`), deparsed that result, and parsed it again (e.g. as `b`) and then verified that `a` == `b`.

Let me know how it goes - happy to help!

**Comment by fortytw2** [comment]
awesome, I'll give it a shot once I have some time. Running it against the SQL found in https://github.com/postgres/postgres/tree/master/src/test/regress/sql sounds like an excellent idea, thanks for the suggestion :1st_place_medal:

**Comment by matthewmueller** [comment]
I'd love to see this as well, allows for SQL rules to be easily re-written

**Comment by lfittl** [comment]
@matthewmueller Good to hear someone else who needs it too, that might be enough interest to warrant looking into this soon-ish.

@fortytw2 Did you find time to look at this already - any existing effort on your end we should collaborate on?

**Comment by fortytw2** [comment]
@lfittl no existing effort on my end yet, just did some investigation on how to do it - not a whole lot of time these days :sob: 

If you start working on it, feel free to @ me on any PRs :smile:

**Comment by lfittl** [comment]
This has been implemented in pg_query 2.0!

See the README, or https://pganalyze.com/blog/pg-query-2-0-postgres-query-parser#turning-parse-trees-back-into-sql-using-a-deparser for an example.
