### ISSUE TITLE
 go struct turn back to sql

### ISSUE THREAD

**Issue by alfredo-linux** [pganalyze/pg_query_go#23]
I parse my pgsql to go struct, and I have changed some value of the  struct's members,  How can i make the struct turn back to pgsqls?

**Comment by tpoxa** [comment]
@alfredo-linux  Hi. Did you find solution?

**Comment by ehfeng** [comment]
Duplicate of https://github.com/lfittl/pg_query_go/issues/4, where the author discusses approaches.

**Comment by lfittl** [comment]
This has been implemented now, see this example in the readme: https://github.com/pganalyze/pg_query_go#deparsing-a-parse-tree-back-into-a-sql-statement-experimental
