### ISSUE TITLE
Line and column numbers for syntax errors

### ISSUE THREAD

**Issue by kyleconroy** [pganalyze/pg_query_go#24]
When parsing a invalid query, `Parse` returns an error string starting with "syntax error ...". Would it be possible to get the offset of the syntax error, similar to [SyntaxError](https://golang.org/pkg/encoding/json/#SyntaxError) type in the json package?

Thanks again for the awesome package :) I'm using it to power my new project https://github.com/kyleconroy/sqlc

**Comment by Davincible** [comment]
Would be really nice to get this working. Then the results can be used as LSP

**Comment by StevenACoffman** [comment]
@kyleconroy The `parser.Error` type has an `Error()` method that only includes the message, but that same `parser.Error` type has all the other fields public.

+ https://github.com/pganalyze/pg_query_go/blob/main/parser/parser.go#LL106C15-L106C38
Appears to call:
+ https://github.com/pganalyze/pg_query_go/blob/7986455fd7e1752b8399930d49beac2e8a139bd5/parser/pg_query_parse.c#L110
+ Appears to call:
https://github.com/pganalyze/pg_query_go/blob/7986455fd7e1752b8399930d49beac2e8a139bd5/parser/pg_query_parse.c#L110

So it looks like a PgQueryError error has:
```
		error = malloc(sizeof(PgQueryError));
		error->message   = strdup(error_data->message);
		error->filename  = strdup(error_data->filename);
		error->funcname  = strdup(error_data->funcname);
		error->context   = NULL;
		error->lineno    = error_data->lineno;
		error->cursorpos = error_data->cursorpos;

		result.error = error;	
```
Which then is read by 
```
func newPgQueryError(errC *C.PgQueryError) *Error {
	err := &Error{
		Message:   C.GoString(errC.message),
		Lineno:    int(errC.lineno),
		Cursorpos: int(errC.cursorpos),
	}
	if errC.funcname != nil {
		err.Funcname = C.GoString(errC.funcname)
	}
	if errC.filename != nil {
		err.Filename = C.GoString(errC.filename)
	}
	if errC.context != nil {
		err.Context = C.GoString(errC.context)
	}
	return err
}
```

So the `parser.Error` should be fully populated:
```
type Error struct {
	Message   string // exception message
	Funcname  string // source function of exception (e.g. SearchSysCache)
	Filename  string // source of exception (e.g. parse.l)
	Lineno    int    // source of exception (e.g. 104)
	Cursorpos int    // char in query at which exception occurred
	Context   string // additional context (optional, can be NULL)
}
```

**Comment by StevenACoffman** [comment]
I believe https://github.com/pganalyze/pg_query_go/pull/76 fixes this issue and this issue can now be closed.

**Comment by lfittl** [comment]
@StevenACoffman Good catch - yes, I think this can be closed. I'm in the process of doing a 4.2.1 release, so this should also be officially released soon.
