### ISSUE TITLE
Upgrade PostgreSQL to version 12

### ISSUE THREAD

**Issue by kyleconroy** [pganalyze/pg_query_go#26]
I'm using pg_query_go to power the PostgreSQL support in https://github.com/kyleconroy/sqlc. Someone ran into an issue where their CREATE TRIGGER statement was failing to parse because they used new syntax introduced in PostgreSQL 11. 

Are there plans to upgrade the parser to the current version of PostgreSQL?

**Comment by kyleconroy** [comment]
Looks like a second user ran into the same problem, this time using [generated columns](https://www.postgresql.org/docs/12/ddl-generated-columns.html), which were added in PostgreSQL 12.

**Comment by kyleconroy** [comment]
A third user has run into this problem, this time due to `PARTITION BY HASH`.

https://github.com/kyleconroy/sqlc/issues/352

**Comment by kyleconroy** [comment]
See work on the upstream parser here: https://github.com/lfittl/libpg_query/pull/67

**Comment by lfittl** [comment]
This has been resolved, with pg_query 2.0 being released today (based on the Postgres 13 parser) - thanks for your patience on this @kyleconroy!
