### ISSUE TITLE
libpg_query/srcdata/enum_defs.json   has none NOT_EXPR

### ISSUE THREAD

**Issue by ultrazgq** [pganalyze/pg_query_go#31]
https://codeload.github.com/lfittl/libpg_query/tar.gz/10-1.0.5
libpg_query/srcdata/enum_defs.json  
![image](https://user-images.githubusercontent.com/5226795/111647847-c9812a00-883d-11eb-881e-326dd3063537.png)
has none NOT_EXPR

![image](https://user-images.githubusercontent.com/5226795/111647950-df8eea80-883d-11eb-89a6-5137efacf564.png)

**Comment by lfittl** [comment]
@ultrazgq Thanks for the report - this has been fixed in the 13 release:

https://github.com/pganalyze/libpg_query/blob/13-latest/srcdata/enum_defs.json#L1570
