### ISSUE TITLE
Implement deparse

### ISSUE THREAD

**Issue by aviaoh** [pganalyze/pg_query_go#4]
Hi @lfittl,

I would like to implement query deparsing, and wondered if the `_deparse.go` files can be edited. Assuming there is no way to auto generate them, we can set the `overwrite` flag to false only for these files.
Also, couldn't find any _how to contribute_ section. Are there any specific guidelines I should follow before opening PR?

Thanks!

**Comment by lfittl** [comment]
@aviaoh Apologies for the slow response here!

I've been thinking for a while if it wouldn't be good to share deparsing logic between the Go library and the Ruby library, which has a fairly complete set of deparsing rules: https://github.com/lfittl/pg_query/blob/master/lib/pg_query/deparse.rb

Whats your use case - are you looking to cover a particular set of SQL statements (e.g. trying to deparse a schema), or looking for a complete set?

In any case, there is currently no specific guidelines for contributions - if you have an idea of how it could work, please feel free to hack away and submit PRs as you go :)

**Comment by avinoamr** [comment]
@lfittl Perhaps we should implement it in libpg_query to make it re-usable for all libraries? Should be simple enough, right? We can port the Ruby code to C.

**Comment by lfittl** [comment]
@avinoamr Possibly - the difficulty with doing that is that you'd need to convert the data structure from the language back into something portable (e.g. JSON) and then read that on the C side, before doing the deparsing.

I suspect that doing the JSON parsing in C (and turning it into some data structure) is going to take most of the effort.

I've been thinking about potentially using protocol buffers as the interchange format, so we can have auto-generated structs in most languages. That said, its probably also some effort to do this.

All in all, its probably easiest for now to add something solely on the Go side that reflects what the Ruby side does - without doing a roundtrip into the C library.

**Comment by tejasmanohar** [comment]
@lfittl I just started looking into implementing this. Would you generate the deparse functionality in the Ruby script that generates the rest of the Nodes? Haven't been able to find the necessary information in the `srcdata` JSON but just wanted to check if I'm missing anything.

**Comment by lfittl** [comment]
@tejasmanohar So its a bit complicated.

There is no deparsing that we can really use inside Postgres right now, so we're left with implementing deparsing ourselves.

I've thought of potentially sharing that logic between languages before (either #1 through a shared definition file, like for the nodes, or #2 by de-serializing the node structure into C again and then doing the deparsing there), but haven't had much time to make progress on that.

The Ruby library has a somewhat complete deparsing logic who various folks contributed to over time (in https://github.com/lfittl/pg_query/blob/master/lib/pg_query/deparse.rb) so one could simply port that code to Go, and also translate the unit tests in https://github.com/lfittl/pg_query/blob/master/spec/lib/pg_query/deparse_spec.rb

Thoughts on what you think makes sense?

**Comment by lfittl** [comment]
This has been implemented now in pg_query 2.0!

See the example here: https://github.com/pganalyze/pg_query_go#deparsing-a-parse-tree-back-into-a-sql-statement-experimental

Or the full context on how it works using the new deparser in the C library: https://pganalyze.com/blog/pg-query-2-0-postgres-query-parser#turning-parse-trees-back-into-sql-using-a-deparser

**Comment by kensaggy** [comment]
That's awesome! Thanks for the update and the great work @lfittl ... nice to see the idea of using PB as interchange format has lived through 2017 to see the light of day :)
