### ISSUE TITLE
Go reference badge points to v1

### ISSUE THREAD

**Issue by tsg** [pganalyze/pg_query_go#71]
Hi, first of all, thank you for this project!

I've noticed that the badge in the README points to the v1 godocs, but the README refers to v2. If the intention is to link to v2, I'd be happy to open a PR to update the badge.

**Comment by lfittl** [comment]
@tsg Good catch!

Yeah, a PR would be welcome - note that #69 should be updating it to v4 soon, but we can always get this in place now for v2.

/cc @msepga as an FYI

**Comment by tsg** [comment]
Thanks, I've opened https://github.com/pganalyze/pg_query_go/pull/73. Feel free to close it if #69 goes in quicker, or I'm also happy to update it to v4.
