### ISSUE TITLE
Deparse of index with period (.) in name leads to syntax error

### ISSUE THREAD

**Issue by lwithers** [pganalyze/pg_query_go#77]
Hi,

If I parse and then de-parse the following statement:

```sql
CREATE INDEX "foo.index" ON foo USING btree (bar)
```

then I end up with a result where the index name is unquoted, which is a syntax error:

```sql
CREATE INDEX foo.index ON foo USING btree (bar)
```

PostgresQL (tested on 10.23 and 15.1) reports:

```
postgres=# CREATE INDEX foo.index ON foo USING btree (bar);
ERROR: syntax error at or near "." (SQLSTATE 42601)
```

**Comment by lfittl** [comment]
@lwithers Thanks for the report - that's an oversight in the deparser code, see https://github.com/pganalyze/libpg_query/pull/182
