### ISSUE TITLE
Deparse bug：The table is wrapped in quotes, and the primary key is automatically unquoted

### ISSUE THREAD

**Issue by liuhangyu** [pganalyze/pg_query_go#88]
if true {
		sql := `ALTER TABLE ONLY public."Test1我们123@#$%"
		ADD CONSTRAINT "Test1我们123@#$%_pkey" PRIMARY KEY (c1);`
		result, err := pg_query.Parse(sql)
		if err != nil {
			fmt.Println("Parse err ", err)
			return
		}

		for _, rawStmt := range result.Stmts {
			var (
				tree = &pg_query.ParseResult{
					Version: result.Version,
					Stmts:   []*pg_query.RawStmt{rawStmt},
				}
			)

			stmt, err := pg_query.Deparse(tree)
			if err != nil {
				fmt.Println("Deparse err ", err)
				return
			}
			fmt.Printf("newSQL: %s\n", stmt)
		}
	}

output：
newSQL: ALTER TABLE ONLY public."Test1我们123@#$%" ADD CONSTRAINT Test1我们123@#$%_pkey PRIMARY KEY (c1)

env go：
go 1.19
require github.com/pganalyze/pg_query_go/v4 v4.2.1

**Comment by lfittl** [comment]
@liuhangyu Thanks for the report, this is indeed a bug - I've opened a fix in the underlying C library: https://github.com/pganalyze/libpg_query/pull/195 (once that is merged it will be included when a new release of libpg_query is made, and the Go library is updated)

**Comment by liuhangyu** [comment]
thanks for the reply
