### ISSUE TITLE
index conversion error

### ISSUE THREAD

**Issue by liuhangyu** [pganalyze/pg_query_go#98]
github.com/pganalyze/pg_query_go/v4 v4.2.1

	if true {
		sql := "CREATE INDEX index_epics_on_group_id_and_iid_varchar_pattern ON public.epics USING btree (group_id, ((iid)::character varying) varchar_pattern_ops);"

		result, err := pg_query.Parse(sql) //此处解析sql含有bug，主键名含有引号的给去掉了
		if err != nil {
			fmt.Println(err)
			return
		} else {
			// Deparse back into a query
			stmt, err := pg_query.Deparse(result)
			if err != nil {
				fmt.Println(err)
				return
			}
			fmt.Printf("%s\n", stmt)
		}
	}

ouput:
CREATE INDEX index_epics_on_group_id_and_iid_varchar_pattern ON public.epics USING btree (group_id, iid::varcharvarchar_pattern_ops)

expect：
CREATE INDEX index_epics_on_group_id_and_iid_varchar_pattern ON public.epics USING btree (group_id, ((iid)::character varying) varchar_pattern_ops)

use package：
pg_query "github.com/pganalyze/pg_query_go/v4"

**Comment by lfittl** [comment]
Thanks for the report - linking https://github.com/pganalyze/libpg_query/issues/213 (which you also reported), since this would be a libpg_query issue, not pg_query_go directly.

**Comment by liuhangyu** [comment]
thinks
